// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Testthi.Migrations
{
    [DbContext(typeof(LTQLDb))]
    [Migration("20230621110125_Create_Foreignkey_SanPham")]
    partial class Create_Foreignkey_SanPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("Testthi.Models.NhaCungCap", b =>
                {
                    b.Property<int?>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenNhaCungCap")
                        .HasColumnType("TEXT");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("Testthi.Models.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaNhaCungCap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("TEXT");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("Testthi.Models.SanPham", b =>
                {
                    b.HasOne("Testthi.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNhaCungCap");

                    b.Navigation("NhaCungCap");
                });
#pragma warning restore 612, 618
        }
    }
}
